[base]
#output = "VGA-0"
cursor = false
clipboard = true
file = true
stdout = false
log_level = "info"

[file]
path = "$HOME/screen_dumps"
name_format = "%s"
encoding = "png"

[encoding.png]
compression = "best"
filter = "adaptive"

[encoding.jxl]
lossless = true
distance = 1
effort = 10
