// -*- mode: jsonc -*-
{
	"reload_style_on_change": true,
	"ipc": false,
	"spacing": 0,
    "expand-center": false,
    "margin-top": 0,
	"margin-right": 20,
	"exclusive": false,
	"position": "right",
    "margin-bottom": 0,
	"height": 200,
	"modules-left": [
		"custom/string#1",
		"group/n1"
	],
	"modules-center": [
		"custom/string#2",
		"group/n2"
	],
	"modules-right": [
		"custom/string#3",
		"group/n3"
	],
	"custom/string#1": {
		"tooltip": false,
		"align": 0,
		"format": "RESOURCES ——————————"
	},
	"custom/string#2": {
		"tooltip": false,
		"align": 0,
		"format": "STORAGE ————————————"
	},
	"custom/string#3": {
		"tooltip": false,
		"align": 0,
		"format": "NETWORK ————————————"
	},
	"group/n1": {
		"orientation": "vertical",
		"modules": [
			"cpu",
			"memory"
		]
	},
	"group/n2": {
		"orientation": "vertical",
		"modules": [
			"disk#root",
			"disk#home"
		]
	},
	"group/n3": {
		"orientation": "vertical",
		"modules": [
			"network#local",
			"network#vpn"
		]
	},
	"cpu": {
		"tooltip": false,
		"interval": 5,
		"align": 0,
		"format": "<span size='13.5pt' rise='-1500'>󰻠</span> CPU: {usage}%",
	},
	"memory": {
		"tooltip": false,
		"align": 0,
		"interval": 5,
		"format": "<span size='13.5pt' rise='-1500'>󰘚</span> Memory: {percentage}%\n<span size='13.5pt' rise='-1500'>󰓡</span> Swap: {swapPercentage}%",
	},
	"disk#root": {
		"tooltip": false,
		"align": 0,
		"path": "/",
		"format": "<span size='13.5pt' rise='-1500'></span> Root:\n{used}/{total}\n"
	},
	"disk#home": {
		"tooltip": false,
		"align": 0,
		"path": "/home",
		"format": "<span size='13.5pt' rise='-1500'>󱂵</span> Home:\n{used}/{total}"
	},
	"network#local": {
		"tooltip": false,
		"align": 0,
		"interface": "eth0",
		"format": "<span size='13.5pt' rise='-1500'>󰈀</span> Ethernet:\n{ipaddr}\n"
	},
	"network#vpn": {
		"tooltip": false,
		"align": 0,
		"interface": "tun0",
		"format": "<span size='13.5pt' rise='-1500'>󰖂</span> VPN:\n{ipaddr}"
	}
    }
}
