# full - resized - wal - thumb -  fastresize - kmeans
backend = "fastresize"

# lab - labmixed - lch - lchmixed - salience
color_space = "lchmixed"

# dark - ansidark - dark16 - darkcomp - darkcomp16
# light - light16 - lightcomp - lightcomp16
# harddark - harddark16 - harddarkcomp - harddarkcomp16
# softdark - softdark16 - softdarkcomp - softdarkcomp16
# softlight - softlight16 - softlightcomp - softlightcomp16
# saliencedark - saliencedarkbalanced - saliencedarkdistributed - saliencedarklow (each has the 16 variations)
# salienceligh - saliencelightbalanced - saliencelightdistributed - saliencelightlow (each has the 16 variations)
palette = "saliencedark"

check_contrast = true
alpha = 75
saturation = 45
no_hooks = false

[templates]
waybar = { template = 'waybar', target = '~/.config/waybar/colors.css' }
vibepanel = { template = 'vibepanel', target = '~/.config/vibepanel/config.toml' }
foot = { template = 'foot', target = '~/.config/foot/colors.ini' }
fuzzel = { template = 'fuzzel', target = '~/.config/fuzzel/colors.ini' }
neovim = { template = 'neovim', target = '~/.cache/wal/colors-wal.vim' }
mangowc = { template = 'mangowc', target = '~/.config/mango/colors.conf' }
rofi = { template = 'rofi', target = '~/.config/rofi/colors.rasi' }
dunst = { template = 'dunst', target = '~/.config/dunst/dunstrc.d/colors.conf' }
yazi_flavor = { template = 'yazi_fv', target = '~/.config/yazi/flavors/wallust.yazi/flavor.toml' }
yaz_flavorxml = { template = 'yazi_th', target = '~/.config/yazi/flavors/wallust.yazi/tmtheme.xml' }

[hooks]
mangowc_reload = 'mmsg -d reload_config'
dunst_reload = 'dunstctl reload'
