# full - resized - wal - thumb -  fastresize - kmeans
backend = "kmeans"

# lab - labmixed - lch - lchmixed - salience
color_space = "lab"

# dark - ansidark - dark16 - darkcomp - darkcomp16
# light - light16 - lightcomp - lightcomp16
# harddark - harddark16 - harddarkcomp - harddarkcomp16
# softdark - softdark16 - softdarkcomp - softdarkcomp16
# softlight - softlight16 - softlightcomp - softlightcomp16
# saliencedark - saliencedarkbalanced - saliencedarkdistributed - saliencedarklow (each has the 16 variations)
# salienceligh - saliencelightbalanced - saliencelightdistributed - saliencelightlow (each has the 16 variations)
palette = "saliencedarklow"

#fallback_generator = "complementary"
saturation = 16
threshold = 12
check_contrast = true
no_hooks = false

[templates]
css = { template = 'css', target = '~/.config/colors.css' }
wswitch = { template = 'wswitch', target = '~/.config/wswitch/themes/wallust.ini' }
vibepanel = { template = 'vibepanel', target = '~/.config/vibepanel/style.css' }
foot = { template = 'foot', target = '~/.config/foot/colors.ini' }
neovim = { template = 'neovim', target = '~/.cache/wal/colors-wal.vim' }
mangowc = { template = 'mangowc', target = '~/.config/mango/colors.conf' }
rofi = { template = 'rofi', target = '~/.config/rofi/colors.rasi' }
yazi_flavor = { template = 'yazi_fv', target = '~/.config/yazi/flavors/wallust.yazi/flavor.toml' }
yaz_flavorxml = { template = 'yazi_th', target = '~/.config/yazi/flavors/wallust.yazi/tmtheme.xml' }

[hooks]
notify_and_shit = 'notify-send -i "cs-cat-appearance" "Colos scheme and Wallpaper set!"'
