#------------------#
$mainMod = SUPER
$auxMod = Alt
$midMod = Shift
$minMod = Ctrl
$null =
#-------------------------#
$terminal = footclient
$fileManager = pcmanfm
#-----------------------------------------#
bind = $mainMod, Q, killactive,
bind = $mainMod, F, togglefloating
bind = $mainMod, J, togglesplit
bind = $mainMod, A, layoutmsg, swapsplit
#-------------------------------------------#
bind = $mainMod, F11, fullscreenstate, 0 2
bind = $null, F11, fullscreen
#------------------------------------#
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
#------------------------------------------#
bind = $null, page_down, workspace, e+1
bind = $null, page_up, workspace, e-1
#---------------------------------------#
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
#-----------------------------------------------#
bind = $mainMod $midMod, 1, movetoworkspace, 1
bind = $mainMod $midMod, 2, movetoworkspace, 2
bind = $mainMod $midMod, 3, movetoworkspace, 3
bind = $mainMod $midMod, 4, movetoworkspace, 4
bind = $mainMod $midMod, 5, movetoworkspace, 5
bind = $mainMod $midMod, 6, movetoworkspace, 6
bind = $mainMod $midMod, 7, movetoworkspace, 7
bind = $mainMod $midMod, 8, movetoworkspace, 8
bind = $mainMod $midMod, 9, movetoworkspace, 9
#-----------------------------------------------#
bind = $null, Print, exec, wayshot -g
bind = $mainMod, Print, exec, wayshot
bind = $mainMod $auxMod, R, exec, screenrcrd_toggle
#-----------------------------------------------------#
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
#----------------------------------------------------#
binde = $mainMod $auxMod, right, resizeactive, 50 0
binde = $mainMod $auxMod, left, resizeactive, -50 0
binde = $mainMod $auxMod, up, resizeactive, 0 -50
binde = $mainMod $auxMod, down, resizeactive, 0 50
#-------------------------------------------------#
bind = $mainMod, $mainMod_R, exec, app_launcher
bind = $mainMod, space, exec, connection_select
bind = $mainMod, G, exec, game_launcher
bind = $mainMod $midMod, F12, exec, vpn_toggle
#------------------------------------------------------------------#
bind = $mainMod, return, exec, $terminal
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, C, exec, hyprpicker -a -t
bind = $mainMod $midMod, C, exec, galculator
#------------------------------------------------------------------#
bind = $mainMod, V, exec, $terminal -T wiremix_overlay  sh -c "(cat misc/color_scheme &); wiremix"
bind = $mainMod, M, exec, $terminal -T rmpc_overlay     sh -c "(cat misc/color_scheme &); rmpc"
bind = $mainMod, Y, exec, $terminal -T yazi_overlay     sh -c "(cat ~/.cache/wal/sequences &); yazi"
bind = $mainMod, F12, exec, $terminal -T btop_overlay   sh -c "(cat misc/color_scheme &); btop"
#------------------------------------------------------------------#
bind = $mainMod $midMod, Q, exit
bind = $minMod $auxMod, delete, exec, hyprcfg
#-----------------------------------#

