#-----------------------------------------------------#
exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent 
#--------------------------------------------------#
exec-once = conky
exec-once = easyeffects --service-mode -w
exec-once = foot --server
exec-once = hypridle
exec-once = swww-daemon
exec-once = udiskie
exec-once = waybar
exec-once = wl-paste --watch clipvault store
#---------------------------------------------------------#
