[urgency_low]
    background = "#010101"
    foreground = "#F0F0F0"
    timeout = 5
[urgency_normal]
    background = "#010101"
    foreground = "#F0F0F0"
	frame_color = "#DC7979"
    timeout = 5
    override_pause_level = 30
[urgency_critical]
    background = "#010101"
    foreground = "#F0F0F0"
    frame_color = "#7A4343"
    timeout = 10
    override_pause_level = 60
    default_icon = dialog-warning
