#===============
fullscreen=yes
load-scripts=yes
profile=high-quality
force-window=immediate
demuxer-max-bytes=512MiB
demuxer-cache-wait=yes
embeddedfonts=no
alang=english,eng,en
slang=english,eng,en
http-header-fields='User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
#=====================
vo=gpu
gpu-api=opengl
gpu-context=auto
dither-depth=8
video-sync=display-resample
interpolation=yes
tscale=oversample
scale=ewa_lanczos
scale-radius=3
#==========================================
osd-font='JetBrainsMonoNL Nerd Font Propo'
osd-bold=no
osd-font-size=16
osd-shadow-offset=0
osd-outline-size=0
osd-border-style=background-box
osd-align-x=right
osd-scale=2
osd-scale-by-window=no

osd-bar=no
osd-bar-h=0.5
osd-bar-align-x=0
osd-bar-align-y=-0.85
#======================================================
sub-font='Tinos Nerd Font Propo'
sub-ass-style-overrides=FontName=Tinos Nerd Font Propo
sub-margin-y=86
sub-border-style=background-box
sub-outline-size=1.5
sub-shadow-offset=0
sub-ass-override=yes
#======================
audio-channels=stereo
audio-normalize-downmix=yes
