#===============
force-window=immediate
keep-open=yes
fullscreen=yes
load-scripts=yes
embeddedfonts=no
alang=english,eng,en
slang=english,eng,en
volume-max=200
#==========================================
osd-bold=no
osd-bar=no
osd-font='IBM Plex Sans'
osd-font-size=28
osd-outline-size=1.5
osd-border-style=outline-and-shadow
osd-align-x=center
osd-scale-by-window=no
#======================================================
sub-font='New York Medium'
sub-ass-style-overrides=FontName=New York Medium
sub-font-size=46
sub-pos=99
sub-border-style=outline-and-shadow
sub-outline-size=1.5
sub-ass-override=scale
sub-back-color=black
sub-use-margins=no
#======================
audio-channels=stereo
audio-normalize-downmix=yes
#=================================
vo=gpu
gpu-api=opengl
gpu-context=wayland
dither-depth=8
video-sync=display-resample
interpolation=yes
tscale=oversample
scale=lanczos
#=================================
