# ============================================================
# General behaviour
# ============================================================
fullscreen=yes
load-scripts=yes
force-seekable=yes
keep-open=always
profile=high-quality
force-window=immediate
embeddedfonts=no

# ============================================================
# Display / Video output
# ============================================================
vo=gpu
gpu-api=opengl
gpu-context=wayland
dither-depth=8
video-sync=display-resample
interpolation=no
scale=ewa_lanczos
scale-radius=1.85
sharpen=0

# ============================================================
# OSD (On-Screen Display)
# ============================================================
osd-font='BlexMono Nerd Font Mono'
osd-font-size=16
osd-shadow-offset=0
osd-outline-size=0
osd-border-style=background-box
osd-align-x=right
osd-scale=2
osd-scale-by-window=no

osd-bar=no
osd-bar-h=0.5
osd-bar-align-x=0
osd-bar-align-y=-0.85

# ============================================================
# Subtitles
# ============================================================
sub-font='NotoSans Nerd Font Propo'
sub-margin-y=86
sub-border-style=background-box
sub-outline-size=0
sub-shadow-offset=0

# ============================================================
# Audio
# ============================================================
audio-channels=stereo
audio-normalize-downmix=yes

# ============================================================
# Clipboard / Wayland integration
# ============================================================
clipboard-monitor=yes
clipboard-backends=wayland

