conky.config = {
    alignment = 'middle_right',
    background = true,
    border_width = 1,
    cpu_avg_samples = 2,
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    extra_newline = false,
    gap_x = 120,
    gap_y = 0,
    minimum_height = 5,
    minimum_width = 180,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_wayland = true,
    out_to_x = false,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'desktop',
    own_window_hints = 'undecorated,sticky,below,skip_taskbar,skip_pager',
    own_window_colour= 'black',
    own_window_transparent = false,
	own_window_argb_visual = true,
	own_window_argb_value = 150,
    show_graph_range = false,
    show_graph_scale = false,
    stippled_borders = 0,
    update_interval = 1.0,
    uppercase = false,
    use_spacer = 'none',
    use_xft = true,

    default_color = '070301',
	color0 = '070301',
	color1 = '3E6F8F',

    font = 'JetBrainsMonoNL Nerd Font Propo:size=11:weight=300',
	font0 = 'JetBrainsMonoNL Nerd Font Mono:size=11.25:weight=900',
	font1 = 'JetBrainsMonoNL Nerd Font Propo:size=15:weight=900',
}

conky.text = [[
${font0}SYSTEM${font} ${color1}${hr 1}${color}

  ${color0}${font1}󰻠 ${color}${font}CPU1: ${cpu cpu1}% ${alignr}${color1}${cpubar 8,45}
  ${voffset -15}
  ${color0}${font1}󰻠 ${color}${font}CPU2: ${cpu cpu2}% ${alignr}${color1}${cpubar cpu2 8,45}
  ${voffset -15}
  ${color0}${font1}󰓡 ${color}${font}SWAP: $swapperc% ${alignr}${color1}${swapbar 8,45}
  ${voffset -15}
  ${color0}${font1}󰘚 ${color}${font}RAM: $memperc% ${alignr}${color1}${membar 8,45}${color}

${font0}STORAGE${font} ${color1}${hr 1}${color}

  ${color0}${font1}󰉐 ${color}${font}Root:
  ${fs_free /}/${fs_size /} 
  ${color0}${fs_bar 4,160 /}
  ${voffset -15}
  ${color0}${font1} ${color}${font}Home:
  ${color}${font}${fs_free /home}/${fs_size /home}
  ${color0}${fs_bar 4,160 /home}${color}

${font0}NETWORK${font} ${color1}${hr 1}${color}

  ${color0}${font1}󰈀 ${color}${font}${addrs eth0}
  ${voffset -15}
  ${color0}${font1}󰖂 ${color}${font}${addrs tun0}
]]
