#—————————————————————————————————|
urgentcolor=0xFF008Bff
focuscolor=0xE7CFADff
rootcolor=0x050302ff
bordercolor=0x37322B22
maximizescreencolor=0xAFC2D1ff
globalcolor=0xE7CFADff
overlaycolor=0xE7CFADff
scratchpadcolor=0xE7CFADff
#—————————————————————————————————|
