#---------------------------------------------------------------------------#
monitorrule=name:VGA-1,width:1440,height:900,refresh:60,scale:1,rr:0,vrr:0
#--------------------------------------------------------------------------#
source=~/.config/mango/colors.conf
source=~/.config/mango/variables.conf
source=~/.config/mango/keybinds.conf
source=~/.config/mango/startup.conf
source=~/.config/mango/animations.conf
source=~/.config/mango/windowrules.conf
#----------------------------------------#

#-----------------#
default_nmaster=1
new_is_master=0
smartgaps=0
#---<
default_mfact=0.50
#------------------#
hotarea_size=10
enable_hotarea=0
ov_tab_mode=1
#---<
overviewgappi=5
overviewgappo=30
#---------------------------#
axis_bind_apply_timeout=100
idleinhibit_ignore_visible=0
focus_on_activate=0
drag_tile_to_tile=1
sloppyfocus=1
focus_cross_monitor=0
focus_cross_tag=0
enable_floating_snap=0
#--<
allow_tearing=0
syncobj_enable=1
#--<
cursor_size=24
warpcursor=1
cursor_hide_timeout=3
#--------------------#

#-----------------------#
repeat_rate=50
repeat_delay=260
numlockon=1
xkb_rules_layout=latam
xkb_rules_options=grp:alt_shift_toggle,compose:menu
#-----------------------------------------------------#
mouse_natural_scrolling=1
accel_profile=0
#----------------#
disable_trackpad=1
#--------------------------#

#-----------#
gappih=8
gappiv=8
gappoh=15
gappov=15
#---<
borderpx=1
no_border_when_single=0
focused_opacity=1.0
unfocused_opacity=0.86
#------------------------#

#-----------------------------#
scratchpad_width_ratio=0.97
scratchpad_height_ratio=0.95
#-----------------------------#

#-----------------------------#
tagrule=id:1,layout_name:tile
tagrule=id:2,layout_name:tile
tagrule=id:3,layout_name:tile
tagrule=id:4,layout_name:tile
tagrule=id:5,layout_name:tile
tagrule=id:6,layout_name:tile
tagrule=id:7,layout_name:tile
tagrule=id:8,layout_name:tile
tagrule=id:9,layout_name:tile
#-----------------------------#
