#---------------------------#
bind=SUPER,r,reload_config
#-------------------------------------#
bind=SUPER,Return,spawn,footclient
bind=SUPER,E,spawn,pcmanfm-qt
bind=SUPER,Backspace,spawn,fuzzel_app_menu
bind=SUPER,code:21,spawn,scripts_menu
bind=SUPER,G,spawn,lutris_wrapper
bind=SUPER+SHIFT,G,spawn,lutris_wrapper --refresh
bind=SUPER+SHIFT,F12,spawn,openvpn_init
bind=SUPER,F3,spawn,eq_preset_set
bind=SUPER,C,spawn,hyprpicker -a -t
bind=CTRL+ALT,delete,spawn,mangocfg 
bind=SUPER+ALT,C,spawn_shell,notify-send "$(mmsg -g -c)"
bind=SUPER+SHIFT,D,spawn,check_storage
#-------------------------------------------#
bind=SUPER+SHIFT,R,spawn,screenrcrd_toggle
bind=NONE,Print,spawn,take_screenshot --section
bind=SUPER,Print,spawn,take_screenshot
#---------------------------------------------------------------------------------------------------#
bind=SUPER,V,toggle_named_scratchpad,wiremix_scratchpad,none,footclient -a wiremix_scratchpad wiremix
bind=SUPER,code:35,toggle_named_scratchpad,rmpc_scratchpad,none,footclient -a rmpc_scratchpad rmpc
bind=SUPER,P,toggle_named_scratchpad,mpv_fzf_scratchpad,none,mpv_fzf
bind=SUPER,Y,toggle_named_scratchpad,yazi_scratchpad,none,footclient -a yazi_scratchpad yazi
bind=SUPER,F12,toggle_named_scratchpad,btop_scratchpad,none,footclient -a btop_scratchpad btop
bind=NONE,F12,toggle_named_scratchpad,footclient_scratchpad,none,footclient -a footclient_scratchpad
bind=SUPER,F6,toggle_named_scratchpad,wallpaper_fzf_scratchpad,none,wallpaper_fzf
#------------------------------------------------------------------------------------------------#
bind=SUPER+SHIFT,q,quit
bind=Super,q,killclient,
#---------------------------------#
bind=SUPER,Left,focusdir,left
bind=SUPER,Right,focusdir,right
bind=SUPER,Up,focusdir,up
bind=SUPER,Down,focusdir,down
#--------------------------------------------#
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right
#--------------------------------------------#
bind=ALT,code:49,toggleoverview
bind=SUPER,F,togglefloating
bind=SUPER+SHIFT,M,togglemaximizescreen
bind=NONE,F11,togglefullscreen
bind=SUPER,F11,togglefakefullscreen
bind=SUPER,I,minimized
bind=SUPER,O,toggleoverlay
bind=SUPER,Tab,toggle_scratchpad
bind=SUPER+SHIFT,I,restore_minimized
#-------------------------------------#
bind=SUPER,n,switch_layout
#----------------------------------------#
bind=NONE,Page_Up,viewtoleft_have_client,
bind=NONE,Page_Down,viewtoright_have_client,
#--------------------------------------------#
bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0
#----------------------------#
bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
bind=SUPER+SHIFT,6,tag,6,0
bind=SUPER+SHIFT,7,tag,7,0
bind=SUPER+SHIFT,8,tag,8,0
bind=SUPER+SHIFT,9,tag,9,0
#---------------------------------------#
bind=CTRL+SHIFT,Up,movewin,+0,-50
bind=CTRL+SHIFT,Down,movewin,+0,+50
bind=CTRL+SHIFT,Left,movewin,-50,+0
bind=CTRL+SHIFT,Right,movewin,+50,+0
#------------------------------------#
bind=SUPER+ALT,Up,resizewin,+0,-50
bind=SUPER+ALT,Down,resizewin,+0,+50
bind=SUPER+ALT,Left,resizewin,-50,+0
bind=SUPER+ALT,Right,resizewin,+50,+0
#-------------------------------------------------#
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize
#-----------------------------------------------#
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client
#---------------------------------------------#
