#———————————————————————————|
bind=SUPER,R,reload_config
bind=SUPER,Q,killclient
#———————————————————————————|

#—————————————————————————————————————|
bind=SUPER,Backspace,spawn,apps_drun
bind=SUPER,Return,spawn,footclient
bind=SUPER,E,spawn,pcmanfm-qt
#—»
bind=SUPER+SHIFT,F12,spawn,run_openvpn_daemon
bind=SUPER,code:47,spawn,exec_loginctl_cmd
bind=SUPER,code:20,spawn,modify_misc_dots
bind=SUPER,code:21,spawn,exec_misc_scripts
#—»
bind=SUPER,F3,spawn,easyeffects_dmenu
bind=SUPER,code:94,spawn,easyeffects --bypass-toggle
bind=SUPER+SHIFT,F3,spawn,easyeffects_dmenu --refresh
#—»
bind=SUPER+SHIFT,G,spawn,lutris_dmenu --refresh
bind=SUPER,G,spawn,lutris_dmenu
#—»
bind=SUPER+SHIFT,R,spawn,screencaster
bind=NONE,Print,spawn,screenshooter --section
bind=SUPER,Print,spawn,screenshooter 
#—————————————————————————————————————————————————————————|

#————————————————————————————————|
bind=SUPER,Left,focusdir,left
bind=SUPER,Right,focusdir,right
bind=SUPER,Up,focusdir,up
bind=SUPER,Down,focusdir,down
#————————————————————————————————|

#———————————————————————————————————————————|
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right
#—————————————————————————————————————————————|

#—————————————————————————————————|
bind=SUPER,code:61,toggleglobal
bind=SUPER,F,togglefloating
bind=SUPER,O,toggleoverlay
bind=ALT,TAB,toggleoverview
bind=ALT,code:49,spawn,wswitch next
bind=SUPER,code:48,focusstack,next
bind=SUPER+SHIFT,code:48,focusstack,prev
#—»
bind=SUPER,I,minimized
bind=SUPER,code:49,toggle_scratchpad
bind=SUPER+SHIFT,I,restore_minimized
#—»
bind=SUPER+SHIFT,M,togglemaximizescreen
#———————————————————————————————————————————|
bind=NONE,F11,togglefullscreen
bind=SUPER,F11,togglefakefullscreen
#—————————————————————————————————————|
bind=SUPER,N,switch_layout
#————————————————————————————|

#——————————————————————|
bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0
#———————————————————————————|
bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
bind=SUPER+SHIFT,6,tag,6,0
bind=SUPER+SHIFT,7,tag,7,0
bind=SUPER+SHIFT,8,tag,8,0
bind=SUPER+SHIFT,9,tag,9,0
#———————————————————————————|

#——————————————————————————————————————|
bind=CTRL+SHIFT,Up,movewin,+0,-50
bind=CTRL+SHIFT,Down,movewin,+0,+50
bind=CTRL+SHIFT,Left,movewin,-50,+0
bind=CTRL+SHIFT,Right,movewin,+50,+0
#——————————————————————————————————————|
bind=SUPER+ALT,Up,resizewin,+0,-50
bind=SUPER+ALT,Down,resizewin,+0,+50
bind=SUPER+ALT,Left,resizewin,-50,+0
bind=SUPER+ALT,Right,resizewin,+50,+0
#——————————————————————————————————————————|
bind=SUPER,code:35,viewtoright_have_client
bind=SUPER+SHIFT,code:35,viewtoleft_have_client
#—————————————————————————————————————————————————|
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize
#———————————————————————————————————————————————|
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client
#————————————————————————————————————————————|
