#———————————————————————————————————————————————————————————————————|
windowrule=isfullscreen:1,force_tearing:1,appid:^Minecraft[*].*$
windowrule=isfullscreen:1,force_tearing:1,title:(^Age of Empires 3$|Skyrim|^DARK SOULS$|^Dusklight v.*$)
#—————————————————————————————————————————————————————————————————————————————————————————————————————————|

#———————————————————————————————————————————————————————————————————————————————————|
windowrule=isfakefullscreen:1,title:(^WhatsApp Web.*$|^Discord.*$|^Pinterest$|^X$)
windowrule=isfakefullscreen:1,title:(^Reddit.*$|^Facebook$|^Instagram$)
windowrule=isfakefullscreen:1,title:(^YouTube.*$|^SoundCloud.*$)
windowrule=isfakefullscreen:1,title:(^Gemini.*$|^ChatGPT$)
windowrule=isfakefullscreen:1,title:(^FMHY.*$|^111477$|^SQUID[.]WTF$)
windowrule=isfakefullscreen:1,title:(^GitHub.*$|^Learn.C.[++]|^.*— Documentation$$)
windowrule=isfakefullscreen:1,title:(^Gmail$|^Proton Mail$)
windowrule=isfakefullscreen:1,title:(^Reactive Resume.*$|^Banco de Venezuela$)
#—————————————————————————————————————————————————————————————————————————————————————|

#——————————————————————————————————————————————————————|
windowrule=isfloating:1,title:Preferences,appid:gimp
#—»
windowrule=isfloating:1,width:395,height:500,appid:galculator
#—»
windowrule=isfloating:1,appid:{io.bassi.Amberol|selectdefaultapplication|nwg-look)
#—————————————————————————————————————————————————————————————————————————————————————|
