#———————————————————————————————————————————————————————|
windowrule=width:1023,height:350,appid:kz_thems
windowrule=width:445,height:687,appid:org.gnome.clocks
windowrule=offsety:80,width:800,height:300,appid:kz_mixer
#———————————————————————————————————————————————————————————|

#———————————————————————————————————————————————————————————————————————————————|
bind=SUPER,code:51,toggle_named_scratchpad,org.gnome.clocks,none,gnome-clocks
#—»
bind=SUPER,F6,toggle_named_scratchpad,kz_thems,none,kzpad -thems
#—»
bind=SUPER,V,toggle_named_scratchpad,kz_mixer,none,kzpad -mixer
#—»
bind=SUPER,P,toggle_named_scratchpad,kz_films,none,kzpad -films
#—»
bind=SUPER,F12,toggle_named_scratchpad,kz_tasks,none,kzpad -tasks
#—»
bind=SUPER,Y,toggle_named_scratchpad,kz_files,none,kzpad -files
#—»
bind=NONE,F12,toggle_named_scratchpad,kz_termn,none,kzpad -termn
#—»
bind=SUPER,code:34,toggle_named_scratchpad,kz_music,none,kzpad -music
#———————————————————————————————————————————————————————————————————————|

#————————————————————————————————————————————————————————————————————————————————————————|
windowrule=width:1360,height:1200,appid:kz_(films|music|tasks|files|termn|mixer)
windowrule=isnamedscratchpad:1,appid:kz_(films|music|tasks|files|termn|thems)
windowrule=isnamedscratchpad:1,appid:org.gnome.clocks
#—————————————————————————————————————————————————————————————————————————————|
