#—————————————————————————————————————————————|
exec-once = /usr/lib/soteria-polkit/soteria
exec-once = /usr/lib/xdg-desktop-portal-wlr
#—————————————————————————————————————————————|
exec-once = vibepanel
exec-once = foot -s
#—»
exec-once = udiskie
exec-once = spicymangod --daemonise
exec-once = sleepymangod --daemonise
exec-once = sway-audio-idle-inhibit
#—»
exec-once = awww-daemon
exec-once = vibepanel_loop
exec-once = footserver_loop
exec-once = easyeffects --service-mode -w
#—»
exec-once = mpd-mpris
exec-once = vpn_startup
exec-once = wswitch --daemon
exec-once = wl-paste --watch clipvault store
#——————————————————————————————————————————————|
