#------------------------------------------#
#windowrule=force_tearing:1,appid:^(gamescope)$
#windowrule=isfullscreen:1,appid:^(gamescope)$
#--<
#windowrule=force_tearing:1,appid:^(steam_proton)$
#windowrule=isfullscreen:1,appid:^(steam_proton)$
#--<
#windowrule=force_tearing:1,appid:^(steam_app_default)$
#windowrule=isfullscreen:1,appid:^(steam_app_default)$
#--<
#windowrule=force_tearing:1,appid:^(Minecraft[*].*)$
windowrule=isfullscreen:1,appid:^(Minecraft[*].*)$
#--------------------------------------------------#
windowrule=isfakefullscreen:1,title:^(YouTube.*)$
windowrule=isfakefullscreen:1,title:^(AnimeKAI.*)$
windowrule=isfakefullscreen:1,title:^(Reddit)$
windowrule=isfakefullscreen:1,title:^(HDTV)$
windowrule=isfakefullscreen:1,title:^(Pinterest)$
windowrule=isfakefullscreen:1,title:^(X)$
windowrule=isfakefullscreen:1,title:^(Anna’s Archive.*)$
windowrule=isfakefullscreen:1,title:^(SQUID[.]WTF)$
windowrule=isfakefullscreen:1,title:^(Discord)$
windowrule=isfakefullscreen:1,title:^(.*— Documentation)$
windowrule=isfakefullscreen:1,title:^(Instagram)$
windowrule=isfakefullscreen:1,title:^(Banco de Venezuela)$
windowrule=isfakefullscreen:1,title:^(GitHub)$
windowrule=isfakefullscreen:1,title:^(Messenger)$
windowrule=isfakefullscreen:1,title:^(Gmail)$
windowrule=isfakefullscreen:1,title:^(scloudx)$
windowrule=isfakefullscreen:1,title:^(111477)$
windowrule=isfakefullscreen:1,title:^(ChatGPT)$
windowrule=isfakefullscreen:1,title:^(Gemini.*)$
windowrule=isfakefullscreen:1,title:^(Proton Mail)$
windowrule=isfakefullscreen:1,title:^(ArchWiki)$
windowrule=isfakefullscreen:1,title:^(Facebook)$
windowrule=isfakefullscreen:1,title:^(Hyprland Wiki)$
#------------------------------------------------------------------------#
windowrule=isfloating:1,title:Preferences,appid:gimp
#------------------------------------------------------------------------#
windowrule=isfloating:1,width:450,height:500,appid:org.gnome.Dictionary
windowrule=isfloating:1,width:395,height:500,appid:galculator
#---<
windowrule=isfloating:1,appid:nwg-look
windowrule=isfloating:1,appid:selectdefaultapplication
#--------------------------------------------------------------------#
windowrule=isnamedscratchpad:1,isoverlay:1,width:445,height:687,appid:org.gnome.clocks
windowrule=isnamedscratchpad:1,isoverlay:1,offsety:80,width:800,height:300,appid:wiremix_scratchpad
windowrule=isnamedscratchpad:1,isoverlay:1,width:1023,height:350,appid:wallpaper_fzf_scratchpad
windowrule=isnamedscratchpad:1,isoverlay:1,width:1360,height:1200,appid:mpv_fzf_scratchpad
windowrule=isnamedscratchpad:1,isoverlay:1,width:1360,height:1200,appid:rmpc_scratchpad
windowrule=isnamedscratchpad:1,isoverlay:1,width:1360,height:1200,appid:btop_scratchpad
windowrule=isnamedscratchpad:1,isoverlay:1,width:1360,height:1200,appid:yazi_scratchpad
windowrule=isnamedscratchpad:1,isoverlay:1,width:1360,height:1200,appid:footclient_scratchpad
#--------------------------------------------------------------------#
layerrule=animation_type_open:fade,animation_type_close:fade,layer_name:vibepanel-tooltip
