db_file		"~/.config/mpd/database"
state_file	"~/.config/mpd/state"
music_directory "~/music"

auto_update "yes"

audio_output {
        type            "pipewire"
        name            "PipeWire Sound Server"
}
