[bar]
size = 32
padding = 4
inset = 0
position = "bottom"
border_radius = 0
background_opacity = 0.0

[widgets]
border_radius = 24
background_opacity = 1.0
left = []
right = []
center = [
	"custom-artix_logo",
	{ group = [ "custom-disk", "spacer:4", "cpu" ] },
	"media", "taskbar",
	"weather", "clock", "tray",
	{ group = [ "custom-openvpn", "custom-gamemode", "quick_settings", "notifications" ] }
]

[widgets.custom-artix_logo]
on_click = "applications_menu"
label = ""

[widgets.taskbar]
workspace_separator_label = "number"
show_scratchpad_windows = false
max_windows = 10
icon_size = 24

[widgets.custom-disk]
icon = "devices"
interval = 30
template = "{output}B"
on_click = "footclient bash -c 'dysk; read'"
exec = "dysk --json /home --units=SI | jq -r '.[] | .stats.available'"

[widgets.window_title]
template = "{title}"
empty_text = "—"
max_chars = 26

[widgets.quick_settings]
bluetooth = false
vpn = false
power = false
network = false
idle_inhibitor = false
updates = false

[widgets.media]
art_radius = 18
visualizer = true
template = "{art}{title}{controls}"
max_chars = 20

[weather]
auto_locate = false
latitude = 10.128877817564067
longitude = -66.78012193001523
units = "metric"
wind_units = "m/s"
refresh_interval = 900
[widgets.weather]
show_icon = true

[widgets.clock]
icon = "calendar-today"
format = "%-I:%M %P • %a %-d %B"

[widgets.custom-openvpn]
show_if_interval = 3
on_click = "openvpn_init"
show_if = "pgrep -x openvpn"
icon = "vpn_key"

[widgets.custom-gamemode]
show_if_interval = 3
icon = "input-gaming-symbolic"
show_if = "gamemoded -s | grep 'gamemode is active'"

[theme]
mode = "dark"
ripple = true
shadows = true
animations = true
outline = true
outline_width = 1
outline_opacity = 1.0

[theme.icons]
weight = 500
theme = "material"

[widgets.notifications]
toast_position = "bottom-center"

[osd]
enabled = true
show_value = true

[advanced]
compositor = "auto"
pango_font_rendering = false
